### PR TITLE
Make reading fields public

### PR DESCRIPTION
**Pull request by FliegendeWurst**
Being able to access the readings makes the library a bit more useful ;)

By the way, I would also add a license to the crate.

### CODE REVIEW

**Comment by redvelo** [comment]
LGTM and I would like to apologize for taking such considerable time to respond to this.

**Comment by redvelo** [comment]
I have just licensed the code as GPLv3 I will wait until I have your consent to that licensing before merging this in.

**Comment by FliegendeWurst** [comment]
> I have just licensed the code as GPLv3 I will wait until I have your consent to that licensing before merging this in.

That's fine by me. Did you also ask the author of the [blog post](https://citizen-stig.github.io/2020/05/17/reading-temperature-sensor-in-rust-using-raspberry-pi-gpio.html)? As I understand it, this crate is based on his code. Probably got a notification already https://github.com/citizen-stig/gpio-am2302-rs/pull/1

> LGTM and I would like to apologize for taking such considerable time to respond to this.

Yeah no worries.

By the way, after porting my copy of the algorithm to the newer https://github.com/warthog618/gpiocdev-rs, I noticed that requesting the line twice (output, then input) introduces considerable delay. I had to reconfigure the output request to be an input request instead. Just something to keep in mind if you ever switch to that library and get weird reading failures.

**Comment by redvelo** [comment]
I just created an [issue](https://github.com/citizen-stig/gpio-am2302-rs/issues/2) asking citizen-stig to license his code, I will change this repo to reflect whatever they decide. I am currently several thousands of miles from my gpio devices and don't have the means to test a change of that manner but would ask a PR if you're willing.

**Comment by FliegendeWurst** [comment]
> [...] but would ask a PR if you're willing.

I'll check whether this library works on the hardware I have (in its current state). Only if it doesn't, I'll open a PR to port to the new gpio library.

**Pull request merged**
